services:
  app:
    build: .
    container_name: exam-grader-container
    image: exam-grader-app:latest
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    restart: "no"
