name: exam-grader-app
base: core22
version: '1.0'
summary: Projekt za automatizirano ocjenjivanje ispita s GUI sučeljem
description: |
  Tkinter GUI aplikacija za ocjenjivanje ispita i paralelnu obradu.

grade: devel
confinement: devmode

apps:
  exam-grader-app:
    command: python3 $SNAP/grader_project.py
    extensions: [gnome]
    plugs:
      - home
      - x11
      - desktop
      - desktop-legacy

parts:
  moj-kod:
    plugin: dump
    source: .
    stage-packages:
      - python3
      - python3-tk
