name: Build Snap
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kod
      uses: actions/checkout@v4

    - name: Pokreni cisti build preko LXD-a
      uses: snapcore/action-build@v2

    - name: Spremi .snap file kao artifakt
      uses: actions/upload-artifact@v4
      with:
        name: moj-snap-paket
        path: ./*.snap
