name: Build Snap
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kod
      uses: actions/checkout@v4

    - name: Build Snap paket
      uses: snapcore/action-build@v1
      id: snapcraft
      with:
        use-lxd: true  # OVO SPAŠAVA STVAR - pokreće build u čistom LXD kontejneru koji može instalirati core22

    - name: Spremi .snap file kao artifakt
      uses: actions/upload-artifact@v4
      with:
        name: moj-snap-paket
        path: ${{ steps.snapcraft.outputs.snap }}
